//
//  Studios.swift
//  Kurozora
//
//  Created by Khoren Katklian on 22/02/2020.
//  Copyright © 2020 Kurozora. All rights reserved.
//

import Foundation

enum Studios {
	case none

	// MARK: - Properties
	/// An array containing the string value of all studios.
	static var allString: [String] = ["P.A. Works",
					  "Ordet",
					  "Studio Khara",
					  "Sega",
					  "Production I.G",
					  "Studio 4C",
					  "Creators in Pack TOKYO",
					  "Shirogumi",
					  "Satelight",
					  "Genco",
					  "Kinema Citrus",
					  "ufotable",
					  "Artmic",
					  "POLYGON PICTURES",
					  "Lay-duce",
					  "DAX Production",
					  "Passione",
					  "AIC A.S.T.A.",
					  "office DCI",
					  "Benesse Corporation",
					  "NAZ",
					  "Silver Link",
					  "Gonzo",
					  "AIC Plus+",
					  "Media Factory",
					  "DropWave",
					  "Toho Company",
					  "Production IMS",
					  "Manglobe",
					  "TYO Animations",
					  "J.C. Staff",
					  "Actas",
					  "Brains Base",
					  "Wit Studio",
					  "Ultra Super Pictures",
					  "Kenji Studio",
					  "Kachidoki Studio",
					  "Nomad",
					  "TROYCA",
					  "Studio 3Hz",
					  "Seven Arcs",
					  "Studio Deva Loka",
					  "Arms",
					  "Hoods Entertainment",
					  "CoMix Wave",
					  "Kyoto Animation",
					  "Nippon Ichi Software",
					  "Sunrise",
					  "MAPPA",
					  "Studio Deen",
					  "Studio Unicorn",
					  "Gathering",
					  "Madhouse",
					  "Tatsunoko Productions",
					  "TNK",
					  "Ascension",
					  "Bridge",
					  "Toei Animation",
					  "Project No.9",
					  "Trigger",
					  "Nippon Animation",
					  "Studio Colorido",
					  "Diomedea",
					  "Xebec",
					  "SANZIGEN",
					  "A-1 Pictures",
					  "C-Station",
					  "TMS Entertainment",
					  "Studio Shuka",
					  "Fanworks",
					  "Encourage Films",
					  "Studio Pierrot",
					  "C2C",
					  "Studio Gokumi",
					  "Asahi Production",
					  "AIC",
					  "Fuji TV",
					  "GoHands",
					  "Oriental Light and Magic",
					  "Poncotan",
					  "Shogakukan Productions",
					  "Studio Chizu",
					  "Aniplex",
					  "Telecom Animation Film",
					  "Graphinica",
					  "Trick Block",
					  "VAP",
					  "Bones",
					  "Tezuka Productions",
					  "Feel",
					  "8bit",
					  "Nexus",
					  "Studio Gallop",
					  "Gainax",
					  "Dogakobo",
					  "LIDEN FILMS",
					  "DLE",
					  "SynergySP",
					  "Shaft",
					  "Shin-Ei Animation",
					  "White Fox",
					  "David Production",
					  "Zexcs",
					  "Seven",
					  "Anpro",
					  "TV Tokyo",
					  "Lerche",
					  "Strawberry Meets Pictures",
					  "Studio Ghibli",
					  "Artland"
	]
}
