author: "Khoren Katklian"
author_url: "https://kurozora.app"
copyright: "Copyright © 2018-present Khoren Katklian. All rights reserved. See [license](https://github.com/kiritokatklian/kurozora-app/blob/master/LICENSE)."
readme: README.md

module: Kurozora
module_version: 1.0.0

github_url: "https://github.com/kiritokatklian/kurozora-app"
github_file_prefix: "https://github.com/kiritokatklian/kurozora-app/tree/master"

root_url:
root_url: "https://kiritokatklian.github.io/kurozora-app/"
docset_icon: "Kurozora/Supporting Files/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png"
dash_url: "https://kiritokatklian.github.io/kurozora-app/docs/docsets/Kurozora.xml"

clean: true
min_acl: internal
skip_undocumented: true

xcodebuild_arguments:
  - -workspace
  - Kurozora.xcworkspace
  - -scheme
  - Kurozora
