disabled_rules: # rule identifiers to exclude from running
  - cyclomatic_complexity
  - discarded_notification_center_observer
  - discouraged_direct_init
  - identifier_name
  - implicit_getter
  - file_length
  - force_cast
  - function_body_length
  - large_tuple
  - line_length
  - mark
  - todo
  - multiple_closures_with_trailing_closure
  - redundant_optional_initialization
  - type_body_length
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - Kurozora/R.generated.swift
