disabled_rules: # rule identifiers to exclude from running
  - cyclomatic_complexity
  - discarded_notification_center_observer
  - discouraged_direct_init
  - file_length
  - function_body_length
  - identifier_name
  - implicit_getter
  - large_tuple
  - line_length
  - mark
  - multiple_closures_with_trailing_closure
  - nesting
  - notification_center_detachment
  - todo
  - trailing_comma
  - type_body_length
  - type_name
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
